language: rust
rust:
  - nightly-2020-09-28
cache: cargo
sudo: false
branches:
  only:
    - master
before_script:
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-09-28
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace