[package]
authors = ['Polkadex Team ']
edition = '2018'
license = 'Apache 2.0'
name = 'polkadex'
version = '2.0.0'

[dependencies]
polkadex-mainnet = { path = "../../node/mainnet", optional = true }
polkadex-mainnet-runtime = { path = "../../runtime/mainnet", optional = true }
polkadex-testnet = { path = "../../node/testnet", optional = true }
polkadex-testnet-runtime = { path = "../../runtime/testnet", optional = true }
pallet-generic-asset = { path = "../../pallets/generic_asset", optional = true }
pallet-polkadex = { path = "../../pallets/polkadex", optional = true }

[features]
common = [
    "pallet-generic-asset",
    "pallet-polkadex",
]
mainnet = [
    "common",
    "polkadex-mainnet",
    "polkadex-mainnet-runtime",
]
testnet  = [
    "common",
    "polkadex-testnet",
    "polkadex-testnet-runtime",
]