[package]
name = "engine-rpc"
version = "0.1.0"
authors = ["Polkadex Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
serde = { version = "1.0.101", features = ["derive"], optional = true }
runtime-api = { package="engine-runtime-api", default-features = false, path = "../runtime-api" }
pallet-polkadex = { default-features = false, path = "../", package="polkadex-engine" }
sp-rpc = {version = '2.0.0', default-features = false}
sp-runtime = {version = '2.0.0', default-features = false}
sp-blockchain = {version = '2.0.0', default-features = false}
sp-api = {version = '2.0.0', default-features = false}
sp-arithmetic = {version = '2.0.0', default-features = false}
sp-std = {version = '2.0.0', default-features = false}
sp-core = {version = '2.0.0', default-features = false}
